/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package apm;

import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author V
 */
public class config extends javax.swing.JFrame {

    /**
     * Creates new form config
     */
    public config() {
        initComponents();
        this.setLocationRelativeTo(null);
        URL url = this.getClass().getResource("icone.png");  
        Image iconeTitulo = Toolkit.getDefaultToolkit().getImage(url);  
        this.setIconImage(iconeTitulo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Salvar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 139, 79, 28));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Vermelho", "Azul", "Rosa", "Roxo", "Preto", "Verde", "Amarelo", "Cinza", "Laranja", "Marrom", " " }));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 87, 219, -1));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 56, 219, -1));

        jLabel1.setText("Nome:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 59, -1, -1));

        jLabel2.setText("Cor da fonte :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jLabel3.setText("CONFIGURAÇÕES");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 11, -1, -1));

        jPanel1.setBackground(new java.awt.Color(0, 204, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 320, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 190, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 190));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        //i wanna runaway
        functions func = new functions();
        ResultSet rs = func.execute("SELECT * FROM config;", "SELECT");
        try {
            while (rs.next()) {
                String nome = rs.getString("nome");
                String cor = rs.getString("cor");
                switch (cor) {
                    case "red":cor = "Vermelho";break;
                    case "green":cor = "Verde";break;
                    case "yellow":cor = "Amarelo";break;
                    case "blue":cor = "Azul";break;
                    case "#FF1493":cor = "Rosa";break;
                    case "purple":cor = "Roxo";break;
                    case "black":cor = "Preto";break;
                    case "gray":cor = "Cinza";break;
                    case "orange":cor = "Laranja";break;
                    case "#A52A2A":cor = "Marrom";break;
                }
                jTextField1.setText(nome);
                jComboBox1.setSelectedItem(cor);
            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_formWindowOpened

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String nome_novo = jTextField1.getText();
        String cor = jComboBox1.getSelectedItem().toString();
        String cor_final = "";
         switch (cor) {
                    case "Vermelho":cor_final = "red";break;
                    case "Verde":cor_final = "green";break;
                    case "Amarelo":cor_final = "yellow";break;
                    case "Azul":cor_final = "blue";break;
                    case "Rosa":cor_final = "#FF1493";break;
                    case "Roxo":cor_final = "purple";break;
                    case "Preto":cor_final = "black";break;
                    case "Cinza":cor_final = "gray";break;
                    case "Laranja":cor_final = "orange";break;
                    case "Marrom":cor_final = "#A52A2A";break;
                }
        functions func = new functions();
        func.execute("DELETE FROM config;", "INSERT");
        func.execute("INSERT INTO config VALUES('" + nome_novo + "','" + cor_final + "')", "INSERT");
        JOptionPane.showMessageDialog(this,"Salvo com sucesso!");
        this.dispose();
        checkInsert(nome_novo);
    }//GEN-LAST:event_jButton1ActionPerformed
    public Boolean checkInsert(String nome) {
        Boolean res = false;
        try {
            functions func = new functions();
            ResultSet rs = func.execute("SELECT * FROM config WHERE nome='" + nome + "'", "SELECT");
            rs.first();
            int quant = rs.getRow();
            if (quant >= 1) {
                res = true;
            } else {
                res = false;
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "ERRO = " + e);
        }

        return res;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(config.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(config.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(config.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(config.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new config().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
