/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package apm;

import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author V
 */
public class insert_adesao extends javax.swing.JFrame {

    /**
     * Creates new form insert_etim
     */
    public insert_adesao() {
        initComponents();
        this.setLocationRelativeTo(null);
        URL url = this.getClass().getResource("icone.png");  
        Image iconeTitulo = Toolkit.getDefaultToolkit().getImage(url);  
        this.setIconImage(iconeTitulo);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel12 = new javax.swing.JLabel();
        txt_datapg1 = new javax.swing.JFormattedTextField();
        txt_nome = new javax.swing.JTextField();
        txt_datapg2 = new javax.swing.JFormattedTextField();
        jLabel13 = new javax.swing.JLabel();
        txt_datarec1 = new javax.swing.JFormattedTextField();
        jLabel14 = new javax.swing.JLabel();
        txt_datarec2 = new javax.swing.JFormattedTextField();
        jLabel15 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        txt_responsavelrec = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txt_responsavelrec2 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txt_valorreceber = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_responsavel = new javax.swing.JTextField();
        txt_valorcamiseta = new javax.swing.JTextField();
        txt_datainsc = new javax.swing.JFormattedTextField();
        txt_valorpago = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Californian FB", 0, 18)); // NOI18N
        jLabel12.setText("INSERIR ADESÃO");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 140, -1));

        try {
            txt_datapg1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(txt_datapg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 90, 157, -1));
        getContentPane().add(txt_nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 157, -1));

        try {
            txt_datapg2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(txt_datapg2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 120, 157, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setText("Data 2º pagamento:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, 160, -1));

        try {
            txt_datarec1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(txt_datarec1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 150, 157, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setText("Rec. 1º pagamento:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, 160, -1));

        try {
            txt_datarec2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(txt_datarec2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 210, 157, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setText("Rec. 2º pagamento:");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 210, 160, -1));

        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 90, 250, -1));
        getContentPane().add(txt_responsavelrec, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 180, 157, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel16.setText("Responsavel Recebimento:");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 180, 190, -1));
        getContentPane().add(txt_responsavelrec2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 240, 157, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel17.setText("Responsavel Recebimento:");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 240, 190, -1));

        jButton1.setText("Inserir adesão");
        jButton1.setEnabled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 330, 120, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Curso:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 100, -1));

        txt_valorreceber.setText("R$");
        getContentPane().add(txt_valorreceber, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 60, 157, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Valor à receber:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 60, 140, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Data 1º pagamento:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 90, 160, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Modalidade:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 160, -1));

        jButton2.setText("Camiseta");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 270, 140, -1));

        jButton3.setText("Carterinha");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 270, 160, -1));

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Valor pago:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 170, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Valor apm camiseta:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 200, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Data de inscrição:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 190, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Responsável:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 130, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Nome:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 120, -1));
        jPanel1.add(txt_responsavel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 157, -1));

        txt_valorcamiseta.setText("R$");
        jPanel1.add(txt_valorcamiseta, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 157, -1));

        try {
            txt_datainsc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel1.add(txt_datainsc, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 157, -1));

        txt_valorpago.setText("R$");
        jPanel1.add(txt_valorpago, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 157, -1));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Etim", "Técnico" }));
        jPanel1.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 160, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String nome_curso,modalidade,nome,responsavel,data_ins,valor_apm_camiseta,pago,receber,data_1,data_2,rec_1,respon_rece,rec2,respon_rece2;
        functions func = new functions();
        nome_curso = jComboBox1.getSelectedItem().toString();
        modalidade = jComboBox2.getSelectedItem().toString();
        nome = txt_nome.getText();
        responsavel = txt_responsavel.getText();
        data_ins = txt_datainsc.getText();
        valor_apm_camiseta = txt_valorcamiseta.getText();
        pago = txt_valorpago.getText();
        receber = txt_valorreceber.getText();
        data_1 = txt_datapg1.getText();
        data_2 = txt_datapg2.getText();
        rec_1 = txt_datarec1.getText();
        respon_rece = txt_responsavelrec.getText();
        rec2 = txt_datarec2.getText();
        respon_rece2 = txt_responsavelrec2.getText();
        if(txt_responsavel.getText().equals(""))
        {
            txt_responsavel.setText("-");
        }
        if(txt_responsavelrec.getText().equals(""))
        {
            txt_responsavelrec.setText("-");
        }
        if(txt_responsavelrec2.getText().equals(""))
        {
            txt_responsavelrec2.setText("-");
        }
        try
        {
            func.sql("INSERT INTO adesao_etim VALUES(null,'"+modalidade+"',"
                + "'"+nome_curso+"',"
                + "'"+nome+"',"
                + "'"+responsavel+"',"
                + "'"+data_ins+"',"
                + "'"+valor_apm_camiseta+"',"
                + "'"+pago+"',"
                + "'"+receber+"',"
                + "'"+data_1+"',"
                + "'"+data_2+"',"
                + "'"+rec_1+"',"
                + "'"+respon_rece+"',"
                + "'"+rec2+"',"
                + "'"+respon_rece2+"');");

        }
        catch(Exception e)
        {
            System.out.println(e);
        }

        this.dispose();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        insert_cam frm = new insert_cam();
        frm.nome = ""+txt_nome.getText();
        frm.curso = ""+jComboBox1.getSelectedItem();
        frm.modalidade = ""+jComboBox2.getSelectedItem();
        frm.data = ""+txt_datainsc.getText();
        frm.vpago=""+txt_valorpago.getText();
        frm.vpagar = ""+txt_valorreceber.getText();
        frm.primeiropag = ""+txt_datapg1.getText();
        frm.segundopag = ""+txt_datapg2.getText();
        frm.rc1=""+txt_responsavelrec.getText();
        frm.rc1=""+txt_responsavelrec2.getText();
        frm.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        ped_car frm = new ped_car();
        frm.setVisible(true);
        frm.nome = ""+txt_nome.getText();
        frm.curso = ""+jComboBox1.getSelectedItem();
        jButton1.setEnabled(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
fill();        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public void fill() {
        try {
            functions func = new functions();
            DefaultComboBoxModel lista = new DefaultComboBoxModel();
            String res = func.listCurso("SELECT * FROM curso ORDER BY nome ASC;");
            System.out.println(res);
            String partes[] = res.split("&");
            int i = 0;
            while (i < partes.length) {
                lista.addElement(partes[i]);
                i++;
            }

            jComboBox1.setModel(lista);
        } catch (Exception e) {
            System.out.println(e);
        }
 }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(insert_adesao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(insert_adesao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(insert_adesao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(insert_adesao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new insert_adesao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JFormattedTextField txt_datainsc;
    private javax.swing.JFormattedTextField txt_datapg1;
    private javax.swing.JFormattedTextField txt_datapg2;
    private javax.swing.JFormattedTextField txt_datarec1;
    private javax.swing.JFormattedTextField txt_datarec2;
    private javax.swing.JTextField txt_nome;
    private javax.swing.JTextField txt_responsavel;
    private javax.swing.JTextField txt_responsavelrec;
    private javax.swing.JTextField txt_responsavelrec2;
    private javax.swing.JTextField txt_valorcamiseta;
    private javax.swing.JTextField txt_valorpago;
    private javax.swing.JTextField txt_valorreceber;
    // End of variables declaration//GEN-END:variables
}
