/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package apm;

import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.io.OutputStreamWriter;
import java.net.URL;
import java.sql.ResultSet;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author V
 */
public class pedido_camiseta extends javax.swing.JFrame {

    functions func = new functions();

    /**
     * Creates new form pedidos
     */
    public pedido_camiseta() {
        initComponents();
        this.setLocationRelativeTo(null);
        URL url = this.getClass().getResource("icone.png");
        Image iconeTitulo = Toolkit.getDefaultToolkit().getImage(url);
        this.setIconImage(iconeTitulo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pedido de camiseta");
        setMinimumSize(new java.awt.Dimension(1163, 676));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 126, 1130, 540));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 780, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/apm/Windows-Close-Program-icon (1).png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/apm/pencil-icon.png"))); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jButton5.setText("Pesquisar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 100, 110, 20));

        jPanel1.setBackground(new java.awt.Color(0, 153, 204));

        jPanel2.setBackground(new java.awt.Color(51, 153, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/apm/Excel-icon_1.png"))); // NOI18N
        jButton7.setText("CONVERTER PARA EXCEL");
        jButton7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton7.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/apm/obs.png"))); // NOI18N
        jButton1.setText("OBSERVAÇÃO");
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jButton7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5))
        );

        jButton3.setText("Apagar todos os pedidos");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel7.setText("Curso:");

        jComboBox2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox2ItemStateChanged(evt);
            }
        });
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jLabel1.setText("Pesquisar:");

        jLabel8.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel8.setText("Modelo:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Camisetas", "Babylook", "Regata" }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/apm/math-add-icon (1).png"))); // NOI18N
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/apm/refresh.png"))); // NOI18N
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });

        jLabel2.setText("Total de pedidos:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel8)
                        .addGap(6, 6, 6)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(jLabel9)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(617, 617, 617)
                        .addComponent(jLabel2)
                        .addGap(7, 7, 7)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel8))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel7))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton3)
                            .addComponent(jLabel10)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(5, 5, 5)
                        .addComponent(jLabel1))))
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1160, 680));
        jPanel1.getAccessibleContext().setAccessibleParent(jPanel1);

        getAccessibleContext().setAccessibleParent(this);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        DefaultTableModel tabela = new DefaultTableModel();
        String digita = jTextField1.getText();
        if (digita.equals("")) {
            JOptionPane.showMessageDialog(this, "Digite algo para pesquisar, por favor!");
        } else {
            String selecionado = jComboBox1.getSelectedItem().toString();
            String curso = jComboBox2.getSelectedItem().toString();
            tabela.addColumn("<html><b>CÓDIGO</b></html>");
            tabela.addColumn("<html><b>TAMANHO</b></html>");
            tabela.addColumn("<html><b>COR</b></html>");
            tabela.addColumn("<html><b>QUANTIDADE</b></html>");

            String res = func.listCamiseta("SELECT * FROM camiseta WHERE tamanho LIKE \"%" + digita + "%\" OR qtd LIKE \"%" + digita + "%\" OR cod LIKE \"%" + digita + "%\" OR cor LIKE \"%" + digita + "%\";");
            System.out.println(res);
            String partes[] = res.split("&");
            int i = 0;
            int k = 0;

            try {
                for (i = 0; i < partes.length; i++) {

                    String partes_partes[] = partes[i].split(";");
                    String[] tudo = {partes_partes[0], partes_partes[3], partes_partes[4], partes_partes[5]};
                    tabela.addRow(tudo);

                }
            } catch (Exception e) {
                System.out.println(e);
            }

            jTextField1.setText("");
            jTable1.setModel(tabela);
            int total = jTable1.getRowCount();
            int k2 = 0;
            int total2 = 0;
            while (k2 < total) {
                total2 += Integer.parseInt("" + tabela.getValueAt(k2, 3));
                k2++;
            }
            jLabel3.setText("" + total2);
            verificar_obs();
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        DefaultTableModel tabela = new DefaultTableModel();
        try {
            String selecionado = jComboBox1.getSelectedItem().toString();
            String curso = jComboBox2.getSelectedItem().toString();

            if (selecionado.equals("Camisetas")) {
                tabela.addColumn("<html><b>CÓDIGO</b></html>");
                tabela.addColumn("<html><b>TAMANHO</b></html>");
                tabela.addColumn("<html><b>COR</b></html>");
                tabela.addColumn("<html><b>QUANTIDADE</b></html>");

                String res = func.listCamiseta("SELECT * FROM camiseta WHERE curso='" + curso + "' AND tipo ='Camisetas';");
                System.out.println(res);
                String partes[] = res.split("&");
                int i = 0;
                int k = 0;

                while (partes[i] != null) {
                    String partes_partes[] = partes[i].split(";");
                    String[] tudo = {partes_partes[0], partes_partes[3], partes_partes[4], partes_partes[5]};
                    tabela.addRow(tudo);

                    i++;
                }
            } else if (selecionado.equals("Babylook")) {
                tabela.addColumn("<html><b>CÓDIGO</b></html>");
                tabela.addColumn("<html><b>TAMANHO</b></html>");
                tabela.addColumn("<html><b>COR</b></html>");
                tabela.addColumn("<html><b>QUANTIDADE</b></html>");

                String res = func.listCamiseta("SELECT * FROM camiseta WHERE curso='" + curso + "' AND tipo ='Babylook';");
                String partes[] = res.split("&");
                int i = 0;
                int k = 0;

                while (partes[i] != null) {
                    String partes_partes[] = partes[i].split(";");
                    String[] tudo = {partes_partes[0], partes_partes[3], partes_partes[4], partes_partes[5]};
                    tabela.addRow(tudo);

                    i++;
                }
            } else if (selecionado.equals("Regata")) {
                tabela.addColumn("<html><b>CÓDIGO</b></html>");
                tabela.addColumn("<html><b>TAMANHO</b></html>");
                tabela.addColumn("<html><b>COR</b></html>");
                tabela.addColumn("<html><b>QUANTIDADE</b></html>");

                String res = func.listCamiseta("SELECT * FROM camiseta WHERE curso='" + curso + "' AND tipo ='Regata';");
                String partes[] = res.split("&");
                int i = 0;
                int k = 0;

                while (partes[i] != null) {
                    String partes_partes[] = partes[i].split(";");
                    String[] tudo = {partes_partes[0], partes_partes[3], partes_partes[4], partes_partes[5]};
                    tabela.addRow(tudo);

                    i++;
                }
            }
        } catch (Exception e) {
        }

        jTable1.setModel(tabela);
        int total = jTable1.getRowCount();
        int k2 = 0;
        int total2 = 0;
        while (k2 < total) {
            total2 += Integer.parseInt("" + tabela.getValueAt(k2, 3));
            k2++;
        }
        jLabel3.setText("" + total2);
        verificar_obs();
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
    }//GEN-LAST:event_jTable1MouseClicked

    private void jComboBox2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox2ItemStateChanged
        DefaultTableModel tabela = new DefaultTableModel();
        try {
            String selecionado = jComboBox1.getSelectedItem().toString();
            String curso = jComboBox2.getSelectedItem().toString();

            if (selecionado.equals("Camisetas")) {
                tabela.addColumn("<html><b>CÓDIGO</b></html>");
                tabela.addColumn("<html><b>TAMANHO</b></html>");
                tabela.addColumn("<html><b>COR</b></html>");
                tabela.addColumn("<html><b>QUANTIDADE</b></html>");

                String res = func.listCamiseta("SELECT * FROM camiseta WHERE curso='" + curso + "' AND tipo ='Camisetas';");
                System.out.println(res);
                String partes[] = res.split("&");
                int i = 0;
                int k = 0;

                while (partes[i] != null) {
                    String partes_partes[] = partes[i].split(";");
                    String[] tudo = {partes_partes[0], partes_partes[3], partes_partes[4], partes_partes[5]};
                    tabela.addRow(tudo);

                    i++;
                }
            } else if (selecionado.equals("Babylook")) {
                tabela.addColumn("<html><b>CÓDIGO</b></html>");
                tabela.addColumn("<html><b>TAMANHO</b></html>");
                tabela.addColumn("<html><b>COR</b></html>");
                tabela.addColumn("<html><b>QUANTIDADE</b></html>");

                String res = func.listCamiseta("SELECT * FROM camiseta WHERE curso='" + curso + "' AND tipo ='Babylook';");
                String partes[] = res.split("&");
                int i = 0;
                int k = 0;

                while (partes[i] != null) {
                    String partes_partes[] = partes[i].split(";");
                    String[] tudo = {partes_partes[0], partes_partes[3], partes_partes[4], partes_partes[5]};
                    tabela.addRow(tudo);

                    i++;
                }
            } else if (selecionado.equals("Regata")) {
                tabela.addColumn("<html><b>CÓDIGO</b></html>");
                tabela.addColumn("<html><b>TAMANHO</b></html>");
                tabela.addColumn("<html><b>COR</b></html>");
                tabela.addColumn("<html><b>QUANTIDADE</b></html>");

                String res = func.listCamiseta("SELECT * FROM camiseta WHERE curso='" + curso + "' AND tipo ='Regata';");
                String partes[] = res.split("&");
                int i = 0;
                int k = 0;

                while (partes[i] != null) {
                    String partes_partes[] = partes[i].split(";");
                    String[] tudo = {partes_partes[0], partes_partes[3], partes_partes[4], partes_partes[5]};
                    tabela.addRow(tudo);

                    i++;
                }
            }
        } catch (Exception e) {
        }
        jTable1.setModel(tabela);
        int total = jTable1.getRowCount();
        int k2 = 0;
        int total2 = 0;
        while (k2 < total) {
            total2 += Integer.parseInt("" + tabela.getValueAt(k2, 3));
            k2++;
        }
        jLabel3.setText("" + total2);
        verificar_obs();
    }//GEN-LAST:event_jComboBox2ItemStateChanged

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
    }//GEN-LAST:event_jTextField1KeyReleased

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int res = sn();
        if (res == 0) {
            zerar();
            JOptionPane.showMessageDialog(this, "Sucess");
        } else {
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        fill();
        DefaultTableModel tabela = new DefaultTableModel();
        try {
            String selecionado = jComboBox1.getSelectedItem().toString();
            String curso = jComboBox2.getSelectedItem().toString();

            if (selecionado.equals("Camisetas")) {
                tabela.addColumn("<html><b>CÓDIGO</b></html>");
                tabela.addColumn("<html><b>TAMANHO</b></html>");
                tabela.addColumn("<html><b>COR</b></html>");
                tabela.addColumn("<html><b>QUANTIDADE</b></html>");

                String res = func.listCamiseta("SELECT * FROM camiseta WHERE curso='" + curso + "' AND tipo ='Camisetas';");
                System.out.println(res);
                String partes[] = res.split("&");
                int i = 0;
                int k = 0;

                while (partes[i] != null) {
                    String partes_partes[] = partes[i].split(";");
                    String[] tudo = {partes_partes[0], partes_partes[3], partes_partes[4], partes_partes[5]};
                    tabela.addRow(tudo);

                    i++;
                }
            } else if (selecionado.equals("Babylook")) {
                tabela.addColumn("<html><b>CÓDIGO</b></html>");
                tabela.addColumn("<html><b>TAMANHO</b></html>");
                tabela.addColumn("<html><b>COR</b></html>");
                tabela.addColumn("<html><b>QUANTIDADE</b></html>");

                String res = func.listCamiseta("SELECT * FROM camiseta WHERE curso='" + curso + "' AND tipo ='Babylook';");
                String partes[] = res.split("&");
                int i = 0;
                int k = 0;

                while (partes[i] != null) {
                    String partes_partes[] = partes[i].split(";");
                    String[] tudo = {partes_partes[0], partes_partes[3], partes_partes[4], partes_partes[5]};
                    tabela.addRow(tudo);

                    i++;
                }
            } else if (selecionado.equals("Regata")) {
                tabela.addColumn("<html><b>CÓDIGO</b></html>");
                tabela.addColumn("<html><b>TAMANHO</b></html>");
                tabela.addColumn("<html><b>COR</b></html>");
                tabela.addColumn("<html><b>QUANTIDADE</b></html>");

                String res = func.listCamiseta("SELECT * FROM camiseta WHERE curso='" + curso + "' AND tipo ='Regata';");
                String partes[] = res.split("&");
                int i = 0;
                int k = 0;

                while (partes[i] != null) {
                    String partes_partes[] = partes[i].split(";");
                    String[] tudo = {partes_partes[0], partes_partes[3], partes_partes[4], partes_partes[5]};
                    tabela.addRow(tudo);

                    i++;
                }
            }
        } catch (Exception e) {
        }

        jTable1.setModel(tabela);
        int total = jTable1.getRowCount();
        int k2 = 0;
        int total2 = 0;
        while (k2 < total) {
            total2 += Integer.parseInt("" + tabela.getValueAt(k2, 3));
            k2++;
        }
        jLabel3.setText("" + total2);
        verificar_obs();
    }//GEN-LAST:event_formWindowOpened

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        String tipo = jComboBox1.getSelectedItem().toString();
        String curso = jComboBox2.getSelectedItem().toString();
        int selecionado = jTable1.getSelectedRow();
        if (selecionado < 0) {
            JOptionPane.showMessageDialog(this, "Selecione um dado para deletar!");
        } else {
            String cod = jTable1.getValueAt(selecionado, 0).toString();
            String sql = "DELETE FROM camiseta WHERE cod=" + cod + ";";
            func.sql(sql);
            pedido_camiseta frm = new pedido_camiseta();
            frm.setVisible(true);
            frm.jComboBox1.setSelectedItem(tipo);
            frm.jComboBox2.setSelectedItem(curso);
            this.dispose();
        }
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        String tipo = jComboBox1.getSelectedItem().toString();
        int selecionado = jTable1.getSelectedRow();
        if (selecionado < 0) {
            JOptionPane.showMessageDialog(this, "Selecione um dado para editar!");
        } else {
            int i = 0;
            int qtd_cols = jTable1.getColumnCount();

            String valores[] = new String[100];
            String items = "";
            while (i < qtd_cols) {
                valores[i] = jTable1.getValueAt(selecionado, i).toString();
                i++;
            }
            int k = 0;
            int p = 0;
            try {
                while (valores[k] != null) {
                    p += 1;
                    k++;
                }
            } catch (Exception e) {
            }
            i = 0;
            String data = "";
            while (i < k) {
                data += valores[i] + ";";
                i++;
            }
            i = 0;

            try {
                while (jTable1.getColumnName(i).toString() != null) {
                    items += jTable1.getColumnName(i).toString() + ";";
                    i++;
                }
            } catch (Exception e) {
                System.out.println(e);
            }

            editar_ped_cam ed = new editar_ped_cam();
            ed.cod = Integer.parseInt(jTable1.getValueAt(selecionado, 0).toString());
            ed.res = data;
            ed.mod = jComboBox1.getSelectedItem().toString();
            ed.curso2 = jComboBox2.getSelectedItem().toString();
            ed.setVisible(true);
        }
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        new Thread(new Runnable() {
            public void run() {
                String tipo[] = {"Camisetas", "Babylook", "Regata"};
                String tamanho[] = {"PP", "P", "M", "G", "GG", "EX-G"};
                String res_cursos = func.listCurso("SELECT * FROM curso ORDER BY nome ASC");
                String[] cursos = res_cursos.split("&");
                int quant = cursos.length;
                int i = 0;
                int j = 0;
                int k = 0;
                String data = "";

                while (i < quant) {
                    data += cursos[i].toUpperCase() + "\n";
                    j = 0;
                    while (j < tipo.length) {

                        data += tipo[j].toUpperCase() + "\n";
                        k = 0;
                        while (k < tamanho.length) {
                            String sql = func.sum("select sum(qtd) SOMA1 from camiseta where curso='" + cursos[i] + "' and tipo='" + tipo[j] + "' and tamanho='" + tamanho[k] + "'");
                            //String res = listCamiseta("SELECT * FROM camiseta WHERE curso='"+cursos[i]+"' AND tipo='"+tipo[j]+"' AND tamanho='"+tamanho[k]+"';");
                            data += ";" + tamanho[k] + ";" + sql + "\n";
                            k++;
                        }
                        j++;
                    }

                    data += "\n";
                    i++;
                }
                try {
                    File file = new File("Pedido de camiseta.csv");
                    FileWriter printer = new FileWriter(file);
                    printer.write(data);
                    printer.close();
                } catch (Exception e) {
                    System.out.println(e);
                }
                vailogo();
            }
        }).start();

    }//GEN-LAST:event_jButton7ActionPerformed
    public void vailogo() {
        JOptionPane.showMessageDialog(this, "Excel gerado com sucesso!");

    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int selecionado = jTable1.getSelectedRow();
        String codigo = jTable1.getValueAt(selecionado, 0).toString();
        System.out.println(codigo);
        obs ob = new obs();
        ob.cod = removeHTML(codigo);
        ob.tipo = jComboBox1.getSelectedItem().toString();
        ob.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed
    public String removeHTML(String text) {
        String tags[] = {"<html>", "</html>", "<font color=\"red\">", "<font color=\"#cccc00\">", "<font color=\"blue\"", "<font color=\"green\">", "<font color=\"purple\">", "</font>", "<font color=\"\">", "<ul>", "</ul>", "<li>", "</li>"};
        int contador = 0;
        while (contador < tags.length) {
            text = text.replace(tags[contador], "");
            contador++;
        }
        return text;
    }

    public void verificar_obs() {
        String res = func.listObs("SELECT * FROM observacoes WHERE tipo='" + jComboBox1.getSelectedItem() + "'");
        String partes[] = res.split(";");
        int quant = jTable1.getRowCount();
        int i = 0;
        while (i < quant) {
            String cod = jTable1.getValueAt(i, 0).toString();
            int k = 0;
            while (k < partes.length) {
                if (cod.equals(partes[k])) {
                    jTable1.setValueAt("<html><ul><li>" + cod + "</li></ul></html>", i, 0);
                    break;
                } else {

                }
                k++;
            }

            i++;
        }

    }
    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        String valor1 = jComboBox1.getSelectedItem().toString();
        String valor2 = jComboBox2.getSelectedItem().toString();
        this.dispose();
        pedido_camiseta frm = new pedido_camiseta();
        frm.setVisible(true);
        frm.jComboBox1.setSelectedItem(valor1);
        frm.jComboBox2.setSelectedItem(valor2);
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        ped_cam frm = new ped_cam();
        frm.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel9MouseClicked
    public void csv() {
        String colunas = "";
        int i = 0;
        int qtd_colunas = jTable1.getColumnCount();
        while (i < qtd_colunas) {
            colunas += jTable1.getColumnName(i) + ";";
            i++;
        }
        String linhas = "";
        i = 0;
        int k = 0;
        while (i < jTable1.getRowCount()) {
            k = 0;
            while (k < qtd_colunas) {
                linhas += jTable1.getValueAt(i, k) + ";";
                k++;
            }
            linhas += "\n";
            i++;
        }
        try {
            FileOutputStream fos = new FileOutputStream("Pedido de camiseta.csv");
            OutputStreamWriter writer = new OutputStreamWriter(fos, "ISO-8859-1");
            writer.write(colunas + "\n" + linhas);
            writer.close();

        } catch (Exception e) {
            System.out.println(e);
        }

    }

    public void zerar() {
        func.sql2("DROP TABLE camiseta;");
        func.sql2("CREATE TABLE camiseta (\n"
                + "  cod int(11) NOT NULL AUTO_INCREMENT,\n"
                + "  curso varchar(200) NOT NULL,\n"
                + "  tipo varchar(200) NOT NULL,\n"
                + "  tamanho char(4) NOT NULL,\n"
                + "  qtd int(11) DEFAULT NULL,\n"
                + "  PRIMARY KEY (cod));");
    }

    public void fill() {
        try {
            functions func = new functions();
            DefaultComboBoxModel lista = new DefaultComboBoxModel();
            String res = func.listCurso("SELECT * FROM curso ORDER BY nome ASC;");
            System.out.println(res);
            String partes[] = res.split("&");
            int i = 0;
            while (i < partes.length) {
                lista.addElement(partes[i]);
                i++;
            }

            jComboBox2.setModel(lista);
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    public int qualAdesao() {
        int res = 0;
        int i = JOptionPane.showOptionDialog(null,
                "Qual é o tipo de adesão?",
                "Feedback",
                JOptionPane.OK_CANCEL_OPTION,
                JOptionPane.INFORMATION_MESSAGE,
                null,
                new String[]{"Etim", "Técnico", "Camiseta"}, null);
        return i;
    }

    public int sn() {
        int res = 0;
        int i = JOptionPane.showOptionDialog(null,
                "Tem certeza disto?",
                "Feedback",
                JOptionPane.OK_CANCEL_OPTION,
                JOptionPane.INFORMATION_MESSAGE,
                null,
                new String[]{"Sim", "Não"}, null);
        return i;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pedido_camiseta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pedido_camiseta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pedido_camiseta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pedido_camiseta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pedido_camiseta().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    public javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
