/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package apm;

import java.awt.Image;
import java.awt.Toolkit;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.InputStreamReader;
import java.net.URL;
import java.net.URLConnection;
import java.sql.ResultSet;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author V
 */
public class prin extends javax.swing.JFrame {
    Timer timer;
    /**
     * Creates new form prin
     */
    public prin() {
        initComponents();
        this.setLocationRelativeTo(null);
        URL url = this.getClass().getResource("icone.png");  
        Image iconeTitulo = Toolkit.getDefaultToolkit().getImage(url);  
        this.setIconImage(iconeTitulo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        ver2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        curso = new javax.swing.JTextField();
        add = new javax.swing.JButton();
        ver = new javax.swing.JButton();
        apagar = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        ver3 = new javax.swing.JPanel();
        apagar_cnv = new javax.swing.JButton();
        salvar = new javax.swing.JButton();
        cor = new javax.swing.JComboBox();
        nome = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<String>();
        jButton7 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel41 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel12 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        txt_datapg1 = new javax.swing.JFormattedTextField();
        txt_nome = new javax.swing.JTextField();
        txt_datapg2 = new javax.swing.JFormattedTextField();
        jLabel27 = new javax.swing.JLabel();
        txt_responsavel = new javax.swing.JTextField();
        txt_datarec1 = new javax.swing.JFormattedTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        txt_datarec2 = new javax.swing.JFormattedTextField();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        txt_datainsc = new javax.swing.JFormattedTextField();
        jComboBox6 = new javax.swing.JComboBox();
        txt_responsavelrec = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        txt_responsavelrec2 = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        txt_valorcamiseta = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        txt_valorpago = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        txt_valorreceber = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jComboBox7 = new javax.swing.JComboBox();
        jButton5 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jComboBox8 = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jFormattedTextField2 = new javax.swing.JFormattedTextField();
        jLabel17 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel18 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jComboBox3 = new javax.swing.JComboBox();
        jComboBox4 = new javax.swing.JComboBox();
        jComboBox5 = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("APM - ETEC DE NOVA ODESSA");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 153, 204));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });
        jPanel1.setLayout(null);

        ver2.setBackground(new java.awt.Color(0, 204, 255));
        ver2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setText("Nome do curso:");

        add.setText("Adicionar curso");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        ver.setText("Visualizar todos os cursos");
        ver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verActionPerformed(evt);
            }
        });

        apagar.setText("Apagar todos os cursos");
        apagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apagarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ver2Layout = new javax.swing.GroupLayout(ver2);
        ver2.setLayout(ver2Layout);
        ver2Layout.setHorizontalGroup(
            ver2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ver2Layout.createSequentialGroup()
                .addGroup(ver2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ver2Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(curso))
                    .addGroup(ver2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(ver2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(apagar, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                            .addComponent(add, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 80, Short.MAX_VALUE)))
                .addContainerGap())
        );
        ver2Layout.setVerticalGroup(
            ver2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ver2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ver2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(curso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(add)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ver)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(apagar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(ver2);
        ver2.setBounds(40, 30, 280, 130);

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField2KeyReleased(evt);
            }
        });
        jPanel1.add(jTextField2);
        jTextField2.setBounds(90, 330, 660, 20);

        jLabel2.setText("Mensagem:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 330, 110, 14);

        ver3.setBackground(new java.awt.Color(0, 204, 255));
        ver3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ver3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        apagar_cnv.setText("Apagar Conversa");
        apagar_cnv.setPreferredSize(null);
        apagar_cnv.setRequestFocusEnabled(false);
        apagar_cnv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apagar_cnvActionPerformed(evt);
            }
        });

        salvar.setText("Salvar");
        salvar.setPreferredSize(null);
        salvar.setRequestFocusEnabled(false);
        salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarActionPerformed(evt);
            }
        });

        cor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Vermelho", "Azul", "Rosa", "Roxo", "Preto", "Verde", "Amarelo", "Cinza", "Laranja", "Marrom", " " }));
        cor.setPreferredSize(null);
        cor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                corActionPerformed(evt);
            }
        });

        nome.setPreferredSize(null);

        jLabel22.setText("Nome:");
        jLabel22.setAutoscrolls(true);
        jLabel22.setFocusTraversalPolicyProvider(true);
        jLabel22.setPreferredSize(null);

        jLabel23.setText("Cor da fonte :");
        jLabel23.setAutoscrolls(true);
        jLabel23.setFocusTraversalPolicyProvider(true);
        jLabel23.setPreferredSize(null);

        javax.swing.GroupLayout ver3Layout = new javax.swing.GroupLayout(ver3);
        ver3.setLayout(ver3Layout);
        ver3Layout.setHorizontalGroup(
            ver3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ver3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ver3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ver3Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(salvar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ver3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(ver3Layout.createSequentialGroup()
                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ver3Layout.createSequentialGroup()
                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cor, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(apagar_cnv, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        ver3Layout.setVerticalGroup(
            ver3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ver3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(apagar_cnv, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ver3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ver3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(salvar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel1.add(ver3);
        ver3.setBounds(500, 30, 210, 130);

        jLabel21.setBackground(new java.awt.Color(255, 255, 255));
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/apm/Folders-OS-Configure-Metro-icon.png"))); // NOI18N
        jLabel21.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel21MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel21);
        jLabel21.setBounds(720, 140, 24, 30);

        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 170, 740, 150);

        jButton7.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/apm/car.png"))); // NOI18N
        jButton7.setText("Pedidos de carterinha");
        jButton7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton7.setVerifyInputWhenFocusTarget(false);
        jButton7.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton7.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7);
        jButton7.setBounds(450, 0, 260, 80);

        jButton6.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/apm/camisetra.png"))); // NOI18N
        jButton6.setText("Pedidos de camiseta");
        jButton6.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6);
        jButton6.setBounds(450, 90, 260, 70);

        jLabel20.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/apm/settings-icon.png"))); // NOI18N
        jLabel20.setText("Config");
        jLabel20.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel20.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel20.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jLabel20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel20MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel20);
        jLabel20.setBounds(0, 0, 50, 80);

        jButton9.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/apm/pessoa.png"))); // NOI18N
        jButton9.setText("Sócios");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9);
        jButton9.setBounds(290, 90, 150, 70);

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/apm/apm3.png"))); // NOI18N
        jPanel1.add(jLabel24);
        jLabel24.setBounds(40, 80, 360, 90);

        jButton2.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/apm/adesao.png"))); // NOI18N
        jButton2.setText("Adesões");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(220, 0, 220, 80);

        jLabel41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/apm/refresh.png"))); // NOI18N
        jLabel41.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel41MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel41);
        jLabel41.setBounds(720, 0, 40, 32);

        jTabbedPane1.addTab("Principal", jPanel1);

        jTabbedPane3.setBackground(new java.awt.Color(0, 204, 255));

        jPanel12.setBackground(new java.awt.Color(0, 153, 204));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setFont(new java.awt.Font("Californian FB", 0, 18)); // NOI18N
        jLabel19.setText("INSERIR ADESÃO");
        jPanel12.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 140, -1));

        try {
            txt_datapg1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel12.add(txt_datapg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 90, 157, -1));
        jPanel12.add(txt_nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 157, -1));

        try {
            txt_datapg2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel12.add(txt_datapg2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 120, 157, -1));

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel27.setText("Data 2º pagamento:");
        jPanel12.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 120, 180, -1));
        jPanel12.add(txt_responsavel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 157, -1));

        try {
            txt_datarec1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel12.add(txt_datarec1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 150, 157, -1));

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel28.setText("Responsável:");
        jPanel12.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 130, -1));

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel29.setText("Rec. 1º pagamento:");
        jPanel12.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, 170, -1));

        try {
            txt_datarec2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel12.add(txt_datarec2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 210, 157, -1));

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel30.setText("Rec. 2º pagamento:");
        jPanel12.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 210, 170, -1));

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel31.setText("Data de inscrição:");
        jPanel12.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 160, -1));

        try {
            txt_datainsc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel12.add(txt_datainsc, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 157, -1));

        jPanel12.add(jComboBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 90, 250, -1));
        jPanel12.add(txt_responsavelrec, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 180, 157, -1));

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel32.setText("Responsavel Recebimento:");
        jPanel12.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 180, 210, -1));
        jPanel12.add(txt_responsavelrec2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 240, 157, -1));

        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel33.setText("Responsavel Recebimento:");
        jPanel12.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 240, 210, -1));

        jButton3.setText("Inserir adesão");
        jButton3.setEnabled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel12.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 320, 120, -1));

        txt_valorcamiseta.setText("R$");
        jPanel12.add(txt_valorcamiseta, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 157, -1));

        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel34.setText("Valor apm camiseta:");
        jPanel12.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 170, -1));

        txt_valorpago.setText("R$");
        jPanel12.add(txt_valorpago, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 157, -1));

        jLabel35.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel35.setText("Valor pago:");
        jPanel12.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 120, -1));

        jLabel36.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel36.setText("Curso:");
        jPanel12.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 100, -1));

        txt_valorreceber.setText("R$");
        txt_valorreceber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_valorreceberActionPerformed(evt);
            }
        });
        jPanel12.add(txt_valorreceber, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 60, 157, -1));

        jLabel37.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel37.setText("Valor à receber:");
        jPanel12.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, 150, -1));

        jLabel38.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel38.setText("Data 1º pagamento:");
        jPanel12.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, 180, -1));

        jLabel39.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel39.setText("Nome:");
        jPanel12.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 120, -1));

        jLabel40.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel40.setText("Modalidade:");
        jPanel12.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 160, -1));

        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Etim", "Técnico" }));
        jPanel12.add(jComboBox7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 160, -1));

        jButton5.setText("Camiseta");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel12.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 270, 140, -1));

        jButton8.setText("Carterinha");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel12.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 270, 160, -1));

        jTabbedPane3.addTab("Adesão", jPanel12);

        jPanel11.setBackground(new java.awt.Color(0, 153, 204));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel25.setBackground(new java.awt.Color(255, 255, 255));
        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel25.setText("Nome:");
        jPanel11.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 50, -1));
        jPanel11.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 180, -1));

        jLabel26.setBackground(new java.awt.Color(255, 255, 255));
        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel26.setText("Sócio:");
        jPanel11.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 50, -1));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Modalidade:");
        jPanel11.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Curso:");
        jPanel11.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Data:");
        jPanel11.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Quantidade:");
        jPanel11.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));

        try {
            jFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel11.add(jFormattedTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 180, -1));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Modelo:");
        jPanel11.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Tamanho:");
        jPanel11.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, -1));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Cor:");
        jPanel11.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));
        jPanel11.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 180, -1));

        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });
        jPanel11.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 180, -1));

        jTextField9.setText("R$");
        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });
        jPanel11.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, 180, -1));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Valor pago:");
        jPanel11.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 80, -1));

        jTextField10.setText("R$");
        jTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10ActionPerformed(evt);
            }
        });
        jPanel11.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 50, 190, -1));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("Valor à pagar:");
        jPanel11.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 50, 80, -1));

        jTextField11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField11ActionPerformed(evt);
            }
        });
        jPanel11.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 80, 190, -1));

        jComboBox8.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Encomendar", "Encomendado", "Entregar", "Entregue", "Pagamento pendente", " " }));
        jComboBox8.setToolTipText("");
        jPanel11.add(jComboBox8, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 200, 190, -1));

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("Primeiro Pagamento:");
        jPanel11.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, 200, -1));

        jTextField12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField12ActionPerformed(evt);
            }
        });
        jPanel11.add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 110, 190, -1));

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setText("Responsavel Recebimento:");
        jPanel11.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, 180, -1));

        jTextField13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField13ActionPerformed(evt);
            }
        });
        jPanel11.add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 140, 190, -1));

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setText("Segundo Pagamento:");
        jPanel11.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, 190, -1));

        jTextField14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField14ActionPerformed(evt);
            }
        });
        jPanel11.add(jTextField14, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 170, 190, -1));

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setText("Situação:");
        jPanel11.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, 140, -1));

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel16.setText("Responsavel Recebimento:");
        jPanel11.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, 200, -1));

        try {
            jFormattedTextField2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel11.add(jFormattedTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 230, 190, -1));

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel17.setText("Entrega:");
        jPanel11.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 230, 50, -1));

        jButton1.setText("Inserir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel11.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 290, -1, -1));

        jPanel11.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 220, -1));

        jLabel18.setFont(new java.awt.Font("Californian FB", 0, 18)); // NOI18N
        jLabel18.setText("INSERIR CAMISETA");
        jPanel11.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 240, -1));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SIM", "NÃO" }));
        jPanel11.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 180, -1));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Etim", "Técnico" }));
        jPanel11.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 180, -1));

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Camisetas", "Babylook", "Regata" }));
        jComboBox4.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox4ItemStateChanged(evt);
            }
        });
        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });
        jPanel11.add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 180, -1));

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "PP", "P", "M", "G", "GG", "EX-G" }));
        jComboBox5.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox5ItemStateChanged(evt);
            }
        });
        jComboBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox5ActionPerformed(evt);
            }
        });
        jPanel11.add(jComboBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, 180, -1));

        jTabbedPane3.addTab("Camiseta", jPanel11);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 763, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Inserir", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void apagar_cnvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apagar_cnvActionPerformed
        functions func = new functions();
        DefaultListModel model = new DefaultListModel();
        model.addElement("");
        jList1.setModel(model);
        func.delete();
        get();
    }//GEN-LAST:event_apagar_cnvActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        functions func = new functions();
        String curso2 = curso.getText();
        if (curso2.equals("")) {
            JOptionPane.showMessageDialog(this, "Digite o curso para adicionar!");
        } else {
            String res = "INSERT INTO curso VALUES('" + curso2 + "');";
            func.sql(res);
        }
    }//GEN-LAST:event_addActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        pedido_camiseta frm = new pedido_camiseta();
        frm.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        pedido_carteira frm = new pedido_carteira();
        frm.setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jTextField2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyReleased
        int lastIndex = jList1.getModel().getSize() - 1;
        if (lastIndex >= 0) {
            jList1.ensureIndexIsVisible(lastIndex);
        }
    }//GEN-LAST:event_jTextField2KeyReleased
    public String txt() {
        String res = "";
        try {
            FileReader arq = new FileReader("chat_config.txt");
            BufferedReader lerArq = new BufferedReader(arq);

            String linha = lerArq.readLine(); // lê a primeira linha
// a variável "linha" recebe o valor "null" quando o processo
// de repetição atingir o final do arquivo texto
            while (linha != null) {
                res += linha;
                linha = lerArq.readLine(); // lê da segunda até a última linha
            }

            arq.close();
        } catch (Exception e) {
            System.out.println(e);
        }
        return res;
    }
    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        String text = jTextField2.getText();
        functions func = new functions();
        String res = txt();
        String partes[] = res.split(";");
        String cor_chat = partes[1];
        String nome_chat = partes[0];
        func.send("<html><font color=\"" + cor_chat + "\">" + nome_chat + "</font>*", text + "</html>");
        System.out.println(cor_chat);
        System.out.println(nome_chat);
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        fill();

        ver2.setVisible(false);
        ver.setVisible(false);
        curso.setVisible(false);
        apagar.setVisible(false);
        add.setVisible(false);
        ver3.setVisible(false);
        apagar_cnv.setVisible(false);
        salvar.setVisible(false);
        cor.setVisible(false);
        nome.setVisible(false);
        int delay = 5000;   // delay de 5 seg.
        int interval = 3000;  // intervalo de 1 seg.
        timer = new Timer();

        timer.scheduleAtFixedRate(new TimerTask() {
            public void run() {
                get();
            }
        }, delay, interval);
        //get();
    }//GEN-LAST:event_formWindowOpened

    private void verActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verActionPerformed
        visualizar_cursos v = new visualizar_cursos();
        v.setVisible(true);
    }//GEN-LAST:event_verActionPerformed

    private void apagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apagarActionPerformed
        functions func = new functions();
        func.sql2("DROP TABLE curso;");
        func.sql("CREATE TABLE curso (\n"
                + "rm INT(7) NOT NULL,\n"
                + "nome VARCHAR(100) NOT NULL,\n"
                + "curso VARCHAR(200) NOT NULL,\n"
                + "rg VARCHAR(20) NOT NULL,\n"
                + "data_nasc VARCHAR(50) NOT NULL,\n"
                + "validade VARCHAR(50) NOT NULL,\n"
                + "PRIMARY KEY (`rm`)\n"
                + ")");
    }//GEN-LAST:event_apagarActionPerformed

    private void jLabel20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseClicked
        if (ver2.isVisible() == false) {
            jButton9.setEnabled(false);
            jButton6.setEnabled(false);
            jButton7.setEnabled(false);
            jButton2.setEnabled(false);
            ver3.setVisible(false);
            apagar_cnv.setVisible(false);
            salvar.setVisible(false);
            cor.setVisible(false);
            nome.setVisible(false);
            ver2.setVisible(true);
            ver.setVisible(true);
            curso.setVisible(true);
            apagar.setVisible(true);
            add.setVisible(true);
        } else {
            jButton9.setEnabled(true);
            jButton6.setEnabled(true);
            jButton7.setEnabled(true);
            jButton2.setEnabled(true);
            ver2.setVisible(false);
            ver.setVisible(false);
            curso.setVisible(false);
            apagar.setVisible(false);
            add.setVisible(false);
        }
    }//GEN-LAST:event_jLabel20MouseClicked

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        jButton9.setEnabled(true);
        jButton6.setEnabled(true);
        jButton7.setEnabled(true);
        jButton2.setEnabled(true);
        ver2.setVisible(false);
        ver.setVisible(false);
        curso.setVisible(false);
        apagar.setVisible(false);
        add.setVisible(false);
        ver3.setVisible(false);
        apagar_cnv.setVisible(false);
        salvar.setVisible(false);
        cor.setVisible(false);
        nome.setVisible(false);
    }//GEN-LAST:event_jPanel1MouseClicked

    private void salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarActionPerformed
        try {
            File file = new File("chat_config.txt");
            FileWriter printer = new FileWriter(file);
            String cor2 = cor.getSelectedItem().toString();
            String cor_final = "";
            switch (cor2) {
                case "Vermelho":
                    cor_final = "red";
                    break;
                case "Verde":
                    cor_final = "green";
                    break;
                case "Amarelo":
                    cor_final = "yellow";
                    break;
                case "Azul":
                    cor_final = "blue";
                    break;
                case "Rosa":
                    cor_final = "#FF1493";
                    break;
                case "Roxo":
                    cor_final = "purple";
                    break;
                case "Preto":
                    cor_final = "black";
                    break;
                case "Cinza":
                    cor_final = "gray";
                    break;
                case "Laranja":
                    cor_final = "orange";
                    break;
                case "Marrom":
                    cor_final = "#A52A2A";
                    break;
            }
            printer.write(nome.getText() + ";" + cor_final);
            printer.close();
            JOptionPane.showMessageDialog(this, "Salvo com sucesso");
        } catch (Exception e) {
            System.out.println(e);
        }
        /* String nome_novo = nome.getText();
         String cor = cor.getSelectedItem().toString();
         String cor_final = "";
         switch (cor) {
         case "Vermelho":cor_final = "red";break;
         case "Verde":cor_final = "green";break;
         case "Amarelo":cor_final = "yellow";break;
         case "Azul":cor_final = "blue";break;
         case "Rosa":cor_final = "#FF1493";break;
         case "Roxo":cor_final = "purple";break;
         case "Preto":cor_final = "black";break;
         case "Cinza":cor_final = "gray";break;
         case "Laranja":cor_final = "orange";break;
         case "Marrom":cor_final = "#A52A2A";break;
         }
         functions func = new functions();
         func.execute("DELETE FROM config;", "INSERT");
         func.execute("INSERT INTO config VALUES('" + nome_novo + "','" + cor_final + "')", "INSERT");
         JOptionPane.showMessageDialog(this,"Salvo com sucesso!");
         this.dispose();
         //checkInsert(nome_novo);
         */
    }//GEN-LAST:event_salvarActionPerformed

    private void jLabel21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseClicked
        //
        if (ver3.isVisible() == false) {
            jButton9.setEnabled(false);
            jButton6.setEnabled(false);
            jButton7.setEnabled(false);
            jButton2.setEnabled(false);
            ver2.setVisible(false);
            ver.setVisible(false);
            curso.setVisible(false);
            apagar.setVisible(false);
            add.setVisible(false);
            ver3.setVisible(true);
            apagar_cnv.setVisible(true);
            salvar.setVisible(true);
            cor.setVisible(true);
            nome.setVisible(true);
            
        
        } else {
            jButton9.setEnabled(true);
            jButton6.setEnabled(true);
            jButton7.setEnabled(true);
            jButton2.setEnabled(true);
            ver3.setVisible(false);
            apagar_cnv.setVisible(false);
            salvar.setVisible(false);
            cor.setVisible(false);
            nome.setVisible(false);
            
           
        }
    }//GEN-LAST:event_jLabel21MouseClicked

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        jButton6.setEnabled(true);
        jButton7.setEnabled(true);
        jButton2.setEnabled(true);
        ver2.setVisible(false);
        ver.setVisible(false);
        curso.setVisible(false);
        apagar.setVisible(false);
        add.setVisible(false);
        ver3.setVisible(false);
        apagar_cnv.setVisible(false);
        salvar.setVisible(false);
        cor.setVisible(false);
        nome.setVisible(false);
    }//GEN-LAST:event_jList1MouseClicked

    private void corActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_corActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_corActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10ActionPerformed

    private void jTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField11ActionPerformed

    private void jTextField12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField12ActionPerformed

    private void jTextField13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField13ActionPerformed

    private void jTextField14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField14ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        functions func = new functions();
if (jTextField9.getText().equals("")) {
            jTextField9.setText("-");
        }
        if (jTextField10.getText().equals("")) {
            jTextField10.setText("-");
        }
        if (jTextField11.getText().equals("")) {
            jTextField11.setText("-");
        }
        if (jTextField12.getText().equals("")) {
            jTextField12.setText("-");
        }
        if (jTextField13.getText().equals("")) {
            jTextField13.setText("-");
        }
        if (jTextField14.getText().equals("")) {
            jTextField14.setText("-");
        }
        try
        {
            func.sql2("INSERT INTO adesao_camiseta VALUES(null,'"+jTextField1.getText()+"',"
                + "'"+jComboBox2.getSelectedItem()+"',"
                + "'"+jComboBox3.getSelectedItem()+"',"
                + "'"+jComboBox1.getSelectedItem()+"',"
                + "'"+jFormattedTextField1.getText()+"',"
                + "'"+jTextField5.getText()+"',"
                + "'"+jComboBox4.getSelectedItem()+"',"
                + "'"+jComboBox5.getSelectedItem()+"',"
                + "'"+jTextField8.getText()+"',"
                + "'"+jTextField9.getText()+"',"
                + "'"+jTextField10.getText()+"',"
                + "'"+jTextField11.getText()+"',"
                + "'"+jTextField12.getText()+"',"
                + "'"+jTextField13.getText()+"',"
                + "'"+jTextField14.getText()+"',"
                + "'"+jComboBox8.getSelectedItem()+"',"
                + "'"+jFormattedTextField2.getText()+"'"
                + ");");
            func.sql("INSERT INTO camiseta VALUES(null,'"+jComboBox1.getSelectedItem()+"','"+jComboBox4.getSelectedItem()+"','"+jComboBox5.getSelectedItem()+"','"+jTextField8.getText()+"',"+jTextField5.getText()+")");

        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox4ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox4ItemStateChanged

    }//GEN-LAST:event_jComboBox4ItemStateChanged

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed

    }//GEN-LAST:event_jComboBox4ActionPerformed

    private void jComboBox5ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox5ItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox5ItemStateChanged

    private void jComboBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        //VITOORRRRR?
        String nome_curso,modalidade,nome,responsavel,data_ins,valor_apm_camiseta,pago,receber,data_1,data_2,rec_1,respon_rece,rec2,respon_rece2;
        functions func = new functions();
        nome_curso = jComboBox6.getSelectedItem().toString();
        modalidade = jComboBox7.getSelectedItem().toString();
        nome = txt_nome.getText();
        responsavel = txt_responsavel.getText();
        data_ins = txt_datainsc.getText();
        valor_apm_camiseta = txt_valorcamiseta.getText();
        pago = txt_valorpago.getText();
        receber = txt_valorreceber.getText();
        data_1 = txt_datapg1.getText();
        data_2 = txt_datapg2.getText();
        rec_1 = txt_datarec1.getText();
        respon_rece = txt_responsavelrec.getText();
        rec2 = txt_datarec2.getText();
        respon_rece2 = txt_responsavelrec2.getText();
        if(txt_responsavel.getText().equals(""))
        {
            txt_responsavel.setText("-");
        }
        if(txt_responsavelrec.getText().equals(""))
        {
            txt_responsavelrec.setText("-");
        }
        if(txt_responsavelrec2.getText().equals(""))
        {
            txt_responsavelrec2.setText("-");
        }
        
        try
        {
            func.sql("INSERT INTO adesao_etim VALUES(null,'"+modalidade+"',"
                + "'"+nome_curso+"',"
                + "'"+nome+"',"
                + "'"+responsavel+"',"
                + "'"+data_ins+"',"
                + "'"+valor_apm_camiseta+"',"
                + "'"+pago+"',"
                + "'"+receber+"',"
                + "'"+data_1+"',"
                + "'"+data_2+"',"
                + "'"+rec_1+"',"
                + "'"+respon_rece+"',"
                + "'"+rec2+"',"
                + "'"+respon_rece2+"');");

        }
        catch(Exception e)
        {
            System.out.println(e);
        }

        this.dispose();
        adesao frm = new adesao();
        frm.dispose();
        frm.jComboBox1.setSelectedItem("Etim");
        frm.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        insert_cam frm = new insert_cam();
        frm.nome = ""+txt_nome.getText();
        frm.curso = ""+jComboBox6.getSelectedItem();
        frm.modalidade = ""+jComboBox7.getSelectedItem();
        frm.data = ""+txt_datainsc.getText();
        frm.vpago=""+txt_valorpago.getText();
        frm.vpagar = ""+txt_valorreceber.getText();
        frm.primeiropag = ""+txt_datapg1.getText();
        frm.segundopag = ""+txt_datapg2.getText();
        frm.rc1=""+txt_responsavelrec.getText();
        frm.rc1=""+txt_responsavelrec2.getText();
        frm.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        ped_car frm = new ped_car();
        frm.setVisible(true);
        frm.nome = ""+txt_nome.getText();
        frm.curso = ""+jComboBox6.getSelectedItem();
        jButton3.setEnabled(true);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        socio frm = new socio();
        frm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       adesao frm = new adesao();
       frm.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
      
    }//GEN-LAST:event_formWindowActivated

    private void jLabel41MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel41MouseClicked
      this.dispose();
      prin frm = new prin();
      frm.setVisible(true);
    }//GEN-LAST:event_jLabel41MouseClicked

    private void txt_valorreceberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_valorreceberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_valorreceberActionPerformed
    public void get() {
        try {
            DefaultListModel lista = new DefaultListModel();
            URL url = new URL("http://etecdenovaodessa.com.br/apm/conversa.txt");
            URLConnection con = url.openConnection();
            con.setDoOutput(true);
            BufferedReader reader = new BufferedReader(new InputStreamReader(con.getInputStream(), "ISO-8859-1"));
            String line = null;
            lista.clear();

            while ((line = reader.readLine()) != null) {
                if (line.equals("<html>")) {
                    break;
                } else {
                    lista.addElement(line);
                }
            }

            jList1.setModel(lista);

        } catch (Exception e) {
            //System.out.println(e);
        }
        String res = txt();
        String partes[] = res.split(";");
        String cor_chat = partes[1];
        String nome_chat = partes[0];
        nome.setText(nome_chat);

        String cor_final = "";
        switch (cor_chat) {
            case "red":
                cor_final = "Vermelho";
                break;
            case "green":
                cor_final = "Verde";
                break;
            case "yellow":
                cor_final = "Amarelo";
                break;
            case "blue":
                cor_final = "Azul";
                break;
            case "#FF1493":
                cor_final = "Rosa";
                break;
            case "purple":
                cor_final = "Roxo";
                break;
            case "black":
                cor_final = "Preto";
                break;
            case "gray":
                cor_final = "Cinza";
                break;
            case "orange":
                cor_final = "Laranja";
                break;
            case "#A52A2A":
                cor_final = "Marrom";
                break;
        }
        cor.setSelectedItem(cor_final);
        /*
         Vermelho
         Azul
         Rosa
         Roxo
         Preto
         Verde
         Amarelo
         Cinza
         Laranja
         Marrom

         */
    }

    public void fill() {
        try {
            functions func = new functions();
            DefaultComboBoxModel lista = new DefaultComboBoxModel();
            String res = func.listCurso("SELECT * FROM curso ORDER BY nome ASC;");
            System.out.println(res);
            String partes[] = res.split("&");
            int i = 0;
            while (i < partes.length) {
                lista.addElement(partes[i]);
                i++;
            }

            jComboBox6.setModel(lista);
            jComboBox1.setModel(lista);
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(prin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(prin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(prin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(prin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new prin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JButton apagar;
    private javax.swing.JButton apagar_cnv;
    private javax.swing.JComboBox cor;
    private javax.swing.JTextField curso;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    public javax.swing.JComboBox jComboBox4;
    public javax.swing.JComboBox jComboBox5;
    private javax.swing.JComboBox jComboBox6;
    private javax.swing.JComboBox jComboBox7;
    private javax.swing.JComboBox jComboBox8;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JFormattedTextField jFormattedTextField2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTextField nome;
    private javax.swing.JButton salvar;
    private javax.swing.JFormattedTextField txt_datainsc;
    private javax.swing.JFormattedTextField txt_datapg1;
    private javax.swing.JFormattedTextField txt_datapg2;
    private javax.swing.JFormattedTextField txt_datarec1;
    private javax.swing.JFormattedTextField txt_datarec2;
    private javax.swing.JTextField txt_nome;
    private javax.swing.JTextField txt_responsavel;
    private javax.swing.JTextField txt_responsavelrec;
    private javax.swing.JTextField txt_responsavelrec2;
    private javax.swing.JTextField txt_valorcamiseta;
    private javax.swing.JTextField txt_valorpago;
    private javax.swing.JTextField txt_valorreceber;
    private javax.swing.JButton ver;
    private javax.swing.JPanel ver2;
    private javax.swing.JPanel ver3;
    // End of variables declaration//GEN-END:variables
}
